# Generated by Django 4.0.4 on 2022-05-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handmedown', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='item',
        ),
        migrations.RemoveField(
            model_name='post',
            name='item_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
