# Generated by Django 4.0.4 on 2022-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handmedown', '0007_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='this is the description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='item_url',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12.14, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='fake@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
